#!/bin/sh

# -----------------------------------------------------------------------------
# INSTALL REQUIRED DEPENDENCIES
# For more details, refer to instructions here:
# https://github.com/birdieapp/birdie/wiki/How-to-compile
# -----------------------------------------------------------------------------

# ARCH LINUX
# There's an official package on the AUR: https://aur.archlinux.org/packages/birdie-git/

# UBUNTU
# sudo apt-get install cmake valac libgtk-3-dev librest-dev libjson-glib-dev libnotify-dev libcanberra-dev libx11-dev libwebkitgtk-3.0-dev libsqlite3-dev libxtst-dev libpurple-dev libgee-dev libdbusmenu-gtk-dev

# FEDORA
# yum install gcc gcc-c++ cmake vala libgee06-devel rest-devel libcanberra-devel libsqlite3x-devel libXtst-devel libpurple-devel libdbusmenu-devel json-glib-devel libnotify-devel webkitgtk3-devel libwnck3-devel

# -----------------------------------------------------------------------------
# BUILDING
# -----------------------------------------------------------------------------

git clone https://github.com/birdieapp/birdie.git
cd birdie
mkdir build
cd build
cmake .. -DCMAKE_INSTALL_PREFIX=/usr
make
sudo make install
