#!/bin/sh

# -----------------------------------------------------------------------------
# INSTALL REQUIRED DEPENDENCIES

# elementary OS
# sudo apt-get install cmake valac libgtk-3-dev libgranite-dev librest-dev libjson-glib-dev libpurple-dev libnotify-dev libcanberra-dev libx11-dev libwebkit2gtk-4.0-dev libsqlite3-dev libxtst-dev libpurple-dev libgee-0.8-dev libdbusmenu-gtk-dev libgtksourceview-3.0-dev

# -----------------------------------------------------------------------------
# BUILDING
# -----------------------------------------------------------------------------

git clone https://github.com/amuza/birdie.git
cd birdie
meson build --prefix=/usr
ninja test
sudo ninja install
